// ═══════════════════════════════════════════════════════════════════
// Source of truth: daftar pekerjaan generus (45 bucket spesifik)
// Import oleh server (statistik normalisasi) & frontend (dropdown).
// ═══════════════════════════════════════════════════════════════════

export type PekerjaanGroup = { label: string; items: string[] };

// ── 7 kelompok (dropdown grouped) ──
export const PEKERJAAN_GROUPS: PekerjaanGroup[] = [
  {
    label: "Non-kerja",
    items: ["Pelajar / Mahasiswa / Belum Bekerja"],
  },
  {
    label: "Pendidikan & Dakwah",
    items: ["Guru Honorer", "Guru Swasta", "Guru Ngaji / Ustadz", "Dosen", "Tenaga Amal Sholih"],
  },
  {
    label: "Pemerintahan & Keamanan",
    items: ["PNS", "Pegawai Honorer Pemerintah", "TNI / Polri"],
  },
  {
    label: "Profesional & Karyawan",
    items: [
      "Karyawan Swasta", "Karyawan BUMN", "Tenaga Kesehatan", "Security / Satpam",
      "Programmer / IT", "Design Grafis", "Videografer", "Wartawan",
      "Akuntan", "Pengacara", "Notaris", "Makelar / Agen",
      "Social Media & E-commerce Specialist", "Marketing", "Public Relations",
      "Konsultan", "Fotografer",
    ],
  },
  {
    label: "Wirausaha & Dagang",
    items: ["Pengusaha", "Pedagang", "Wiraswasta", "Petani / Pekebun", "Peternak", "Nelayan"],
  },
  {
    label: "Gig, Transportasi & Teknis",
    items: [
      "Ojek Online", "Driver Taksi Online", "Kurir", "Supir / Driver Angkutan",
      "Masinis / Supir Kereta", "Operator Pabrik / Buruh", "Petugas Gudang / Logistik",
      "Pekerja Lepas", "Tukang Bangunan", "Tukang Servis AC", "Montir / Bengkel",
      "Pekerja Kopi Keliling",
    ],
  },
  {
    label: "Jasa & Perawatan",
    items: [
      "Rias / Salon / Kecantikan", "Cat Sitter / Pet Sitter", "Juru Masak / Koki",
      "Pelayan / Barista / F&B", "Tukang Cukur / Barber",
      "Baby Sitter / Pengasuh Anak", "Pembantu / Asisten Rumah Tangga",
    ],
  },
];

// ── Flat list semua bucket (untuk pencarian / fallback) ──
export const PEKERJAAN_OPTIONS: string[] = PEKERJAAN_GROUPS.flatMap((g) => g.items);

// ═══════════════════════════════════════════════════════════════════
// Normalisasi: teks bebas → bucket (atau "Lainnya")
// ═══════════════════════════════════════════════════════════════════

const STOP = ["", "-", "—", "–", "n/a", "na", "tidak ada", "belum diisi", "kosong", "?"];

// Alias exact (lowercase) → bucket canonical
const ALIAS: Record<string, string> = {
  // ── Non-kerja ──
  pelajar: "Pelajar / Mahasiswa / Belum Bekerja",
  siswa: "Pelajar / Mahasiswa / Belum Bekerja",
  siswi: "Pelajar / Mahasiswa / Belum Bekerja",
  santri: "Pelajar / Mahasiswa / Belum Bekerja",
  mahasiswa: "Pelajar / Mahasiswa / Belum Bekerja",
  mahasiswi: "Pelajar / Mahasiswa / Belum Bekerja",
  kuliah: "Pelajar / Mahasiswa / Belum Bekerja",
  sekolah: "Pelajar / Mahasiswa / Belum Bekerja",
  sma: "Pelajar / Mahasiswa / Belum Bekerja",
  smk: "Pelajar / Mahasiswa / Belum Bekerja",
  smp: "Pelajar / Mahasiswa / Belum Bekerja",
  sd: "Pelajar / Mahasiswa / Belum Bekerja",
  "sedang menempuh perguruan tinggi": "Pelajar / Mahasiswa / Belum Bekerja",
  "lulusan sma": "Pelajar / Mahasiswa / Belum Bekerja",
  "belum bekerja": "Pelajar / Mahasiswa / Belum Bekerja",
  "tidak bekerja": "Pelajar / Mahasiswa / Belum Bekerja",
  "belum kerja": "Pelajar / Mahasiswa / Belum Bekerja",
  "mencari kerja": "Pelajar / Mahasiswa / Belum Bekerja",
  "pengangguran": "Pelajar / Mahasiswa / Belum Bekerja",
  "menganggur": "Pelajar / Mahasiswa / Belum Bekerja",
  "nganggur": "Pelajar / Mahasiswa / Belum Bekerja",
  "belum punya kerja": "Pelajar / Mahasiswa / Belum Bekerja",
  "fresh graduate": "Pelajar / Mahasiswa / Belum Bekerja",

  // ── Pendidikan & Dakwah ──
  "guru honorer": "Guru Honorer",
  gtt: "Guru Honorer",
  "guru tidak tetap": "Guru Honorer",
  "guru swasta": "Guru Swasta",
  "guru yayasan": "Guru Swasta",
  "guru ngaji": "Guru Ngaji / Ustadz",
  ustadz: "Guru Ngaji / Ustadz",
  ustadzah: "Guru Ngaji / Ustadz",
  "pengajar ngaji": "Guru Ngaji / Ustadz",
  tpq: "Guru Ngaji / Ustadz",
  tpa: "Guru Ngaji / Ustadz",
  mubaligh: "Guru Ngaji / Ustadz",
  "da'i": "Guru Ngaji / Ustadz",
  murobbi: "Guru Ngaji / Ustadz",
  dosen: "Dosen",
  "amal sholih": "Tenaga Amal Sholih",
  amil: "Tenaga Amal Sholih",
  lazis: "Tenaga Amal Sholih",
  relawan: "Tenaga Amal Sholih",
  "aktivis dakwah": "Tenaga Amal Sholih",

  // ── Pemerintahan & Keamanan ──
  pns: "PNS",
  asn: "PNS",
  aparatur: "PNS",
  "pegawai negeri": "PNS",
  "pegawai honorer": "Pegawai Honorer Pemerintah",
  "honorer pemda": "Pegawai Honorer Pemerintah",
  "honorer desa": "Pegawai Honorer Pemerintah",
  "honorer pemerintah": "Pegawai Honorer Pemerintah",
  tni: "TNI / Polri",
  tentara: "TNI / Polri",
  polisi: "TNI / Polri",
  brimob: "TNI / Polri",
  kodim: "TNI / Polri",
  korem: "TNI / Polri",
  polres: "TNI / Polri",
  militer: "TNI / Polri",

  // ── Profesional & Karyawan ──
  "karyawan swasta": "Karyawan Swasta",
  karyawan: "Karyawan Swasta",
  "pegawai swasta": "Karyawan Swasta",
  staf: "Karyawan Swasta",
  staff: "Karyawan Swasta",
  sales: "Karyawan Swasta",
  kasir: "Karyawan Swasta",
  ob: "Karyawan Swasta",
  "office boy": "Karyawan Swasta",
  "pengisi bbm": "Karyawan Swasta",
  spbu: "Karyawan Swasta",
  operator: "Karyawan Swasta",
  buruh: "Karyawan Swasta",
  "buruh pabrik": "Karyawan Swasta",
  security: "Security / Satpam",
  satpam: "Security / Satpam",
  guard: "Security / Satpam",
  "petugas keamanan": "Security / Satpam",
  "admin kantor": "Karyawan Swasta",
  bumn: "Karyawan BUMN",
  "pegawai bumn": "Karyawan BUMN",
  "perawat": "Tenaga Kesehatan",
  bidan: "Tenaga Kesehatan",
  dokter: "Tenaga Kesehatan",
  apoteker: "Tenaga Kesehatan",
  "analis lab": "Tenaga Kesehatan",
  medis: "Tenaga Kesehatan",
  farmasi: "Tenaga Kesehatan",
  paramedis: "Tenaga Kesehatan",
  "tenaga kesehatan": "Tenaga Kesehatan",
  programmer: "Programmer / IT",
  developer: "Programmer / IT",
  "software engineer": "Programmer / IT",
  "teknisi it": "Programmer / IT",
  "it support": "Programmer / IT",
  "sistem informasi": "Programmer / IT",
  "web developer": "Programmer / IT",
  "mobile developer": "Programmer / IT",
  devops: "Programmer / IT",
  "data engineer": "Programmer / IT",
  "full stack": "Programmer / IT",
  "back end": "Programmer / IT",
  "front end": "Programmer / IT",
  coding: "Programmer / IT",
  "design grafis": "Design Grafis",
  "desain grafis": "Design Grafis",
  "graphic designer": "Design Grafis",
  illustrator: "Design Grafis",
  "ui designer": "Design Grafis",
  "ux designer": "Design Grafis",
  videografer: "Videografer",
  "video editor": "Videografer",
  kameramen: "Videografer",
  filmmaker: "Videografer",
  wartawan: "Wartawan",
  jurnalis: "Wartawan",
  reporter: "Wartawan",
  akuntan: "Akuntan",
  accounting: "Akuntan",
  pembukuan: "Akuntan",
  "staf keuangan": "Akuntan",
  finance: "Akuntan",
  pengacara: "Pengacara",
  advokat: "Pengacara",
  lawyer: "Pengacara",
  "konsultan hukum": "Pengacara",
  notaris: "Notaris",
  ppat: "Notaris",
  makelar: "Makelar / Agen",
  "agen properti": "Makelar / Agen",
  "agen asuransi": "Makelar / Agen",
  broker: "Makelar / Agen",
  "social media specialist": "Social Media & E-commerce Specialist",
  "social media": "Social Media & E-commerce Specialist",
  "ecommerce specialist": "Social Media & E-commerce Specialist",
  "e-commerce": "Social Media & E-commerce Specialist",
  "digital marketing": "Social Media & E-commerce Specialist",
  "content creator": "Social Media & E-commerce Specialist",
  "social media and ecommerce": "Social Media & E-commerce Specialist",
  marketing: "Marketing",
  "public relations": "Public Relations",
  pr: "Public Relations",
  "hubungan masyarakat": "Public Relations",
  "media relations": "Public Relations",
  konsultan: "Konsultan",
  consultant: "Konsultan",
  "pekerja kopi keliling": "Pekerja Kopi Keliling",
  "kopi jago": "Pekerja Kopi Keliling",
  "kopi keliling": "Pekerja Kopi Keliling",
  "barista mobile": "Pekerja Kopi Keliling",
  fotografer: "Fotografer",
  photographer: "Fotografer",
  "foto shooter": "Fotografer",
  "fotografer profesional": "Fotografer",

  // ── Wirausaha & Dagang ──
  pengusaha: "Pengusaha",
  owner: "Pengusaha",
  "pemilik usaha": "Pengusaha",
  direktur: "Pengusaha",
  pedagang: "Pedagang",
  dagang: "Pedagang",
  dagangan: "Pedagang",
  reseller: "Pedagang",
  dropshipper: "Pedagang",
  penjual: "Pedagang",
  warung: "Pedagang",
  wiraswasta: "Wiraswasta",
  wirausaha: "Wiraswasta",
  "usaha sendiri": "Wiraswasta",
  umkm: "Wiraswasta",
  "petani": "Petani / Pekebun",
  "pekebun": "Petani / Pekebun",
  "buruh tani": "Petani / Pekebun",
  peternak: "Peternak",
  ternak: "Peternak",
  nelayan: "Nelayan",

  // ── Gig, Transportasi & Teknis ──
  "ojek online": "Ojek Online",
  ojol: "Ojek Online",
  gojek: "Ojek Online",
  "grab motor": "Ojek Online",
  "taksi online": "Driver Taksi Online",
  maxim: "Driver Taksi Online",
  indrive: "Driver Taksi Online",
  "grab car": "Driver Taksi Online",
  "sopir travel": "Driver Taksi Online",
  kurir: "Kurir",
  "j&t": "Kurir",
  jne: "Kurir",
  "shopee express": "Kurir",
  ekspedisi: "Kurir",
  supir: "Supir / Driver Angkutan",
  "supir pribadi": "Supir / Driver Angkutan",
  "driver pribadi": "Supir / Driver Angkutan",
  busway: "Supir / Driver Angkutan",
  transjakarta: "Supir / Driver Angkutan",
  "supir bus": "Supir / Driver Angkutan",
  "supir kereta": "Masinis / Supir Kereta",
  masinis: "Masinis / Supir Kereta",
  kai: "Masinis / Supir Kereta",
  "operator pabrik": "Operator Pabrik / Buruh",
  "pekerja produksi": "Operator Pabrik / Buruh",
  "staf gudang": "Petugas Gudang / Logistik",
  "petugas gudang": "Petugas Gudang / Logistik",
  warehouse: "Petugas Gudang / Logistik",
  logistik: "Petugas Gudang / Logistik",
  packing: "Petugas Gudang / Logistik",
  "pekerja lepas": "Pekerja Lepas",
  freelancer: "Pekerja Lepas",
  "harian lepas": "Pekerja Lepas",
  borongan: "Pekerja Lepas",
  "tukang bangunan": "Tukang Bangunan",
  "tukang batu": "Tukang Bangunan",
  "tukang kayu": "Tukang Bangunan",
  "kuli bangunan": "Tukang Bangunan",
  "mandor bangunan": "Tukang Bangunan",
  "teknisi ac": "Tukang Servis AC",
  "teknisi elektronik": "Tukang Servis AC",
  montir: "Montir / Bengkel",
  mekanik: "Montir / Bengkel",
  bengkel: "Montir / Bengkel",

  // ── Jasa & Perawatan ──
  rias: "Rias / Salon / Kecantikan",
  salon: "Rias / Salon / Kecantikan",
  kecantikan: "Rias / Salon / Kecantikan",
  mua: "Rias / Salon / Kecantikan",
  "makeup artist": "Rias / Salon / Kecantikan",
  "hair stylist": "Rias / Salon / Kecantikan",
  "tata rias": "Rias / Salon / Kecantikan",
  skincare: "Rias / Salon / Kecantikan",
  "cat sitter": "Cat Sitter / Pet Sitter",
  "pet sitter": "Cat Sitter / Pet Sitter",
  "dog walker": "Cat Sitter / Pet Sitter",
  "perawatan hewan": "Cat Sitter / Pet Sitter",
  "juru masak": "Juru Masak / Koki",
  koki: "Juru Masak / Koki",
  chef: "Juru Masak / Koki",
  pelayan: "Pelayan / Barista / F&B",
  waiter: "Pelayan / Barista / F&B",
  waitress: "Pelayan / Barista / F&B",
  pramusaji: "Pelayan / Barista / F&B",
  barista: "Pelayan / Barista / F&B",
  "kasir restoran": "Pelayan / Barista / F&B",
  "tukang cukur": "Tukang Cukur / Barber",
  barber: "Tukang Cukur / Barber",
  "pangkas rambut": "Tukang Cukur / Barber",
  "hairstylist": "Tukang Cukur / Barber",
  "potong rambut": "Tukang Cukur / Barber",
  "baby sitter": "Baby Sitter / Pengasuh Anak",
  babysitter: "Baby Sitter / Pengasuh Anak",
  pengasuh: "Baby Sitter / Pengasuh Anak",
  "pengasuh anak": "Baby Sitter / Pengasuh Anak",
  pembantu: "Pembantu / Asisten Rumah Tangga",
  art: "Pembantu / Asisten Rumah Tangga",
  "asisten rumah tangga": "Pembantu / Asisten Rumah Tangga",
  domestik: "Pembantu / Asisten Rumah Tangga",

  // ── Sisa umum ──
  swasta: "Karyawan Swasta",
  pekerja: "Karyawan Swasta",
  bekerja: "Karyawan Swasta",
  "sedang bekerja": "Karyawan Swasta",
};

// Keyword regex → bucket (diurutkan dari paling spesifik ke paling umum)
const KEYWORDS: [RegExp, string][] = [
  // Pendidikan & Dakwah
  [/guru\s*honorer|gtt|guru\s*tidak\s*tetap/, "Guru Honorer"],
  [/guru\s*swasta|guru\s*yayasan/, "Guru Swasta"],
  [/ustadz|ustadzah|guru\s*ngaji|pengajar\s*ngaji|tpq|tpa|mubaligh|da.?i|murobbi/, "Guru Ngaji / Ustadz"],
  [/dosen|pengajar\s*(kuliah|universitas)/, "Dosen"],
  [/amal\s*sholih|amil|lazis|relawan.*dakwah|aktivis\s*dakwah/, "Tenaga Amal Sholih"],

  // Pemerintahan & Keamanan
  [/tni|tentara|polisi|brimob|kodim|korem|polres|militer/, "TNI / Polri"],
  [/pns|asn|aparatur|pegawai\s*negeri/, "PNS"],
  [/pegawai\s*honorer|honorer\s*(pemda|desa|kota|kabupaten|kecamatan)/, "Pegawai Honorer Pemerintah"],

  // Profesional — spesifik dulu
  [/social\s*media|ecommerce|e-commerce|digital\s*marketing|content\s*creator/, "Social Media & E-commerce Specialist"],
  [/public\s*relations|^pr$|hubungan\s*masyarakat|media\s*relations/, "Public Relations"],
  [/konsultan|consultant/, "Konsultan"],
  [/kopi\s*keliling|kopi\s*jago|pekerja\s*kopi|barista\s*mobile/, "Pekerja Kopi Keliling"],
  [/fotografer|photographer|foto\s*shooter/, "Fotografer"],
  [/marketing(?!.*sales)/, "Marketing"],
  [/programmer|developer|software\s*(engineer|dev)|teknisi\s*it|it\s*support|sistem\s*informasi|devops|data\s*engineer|full\s*stack|back\s*end|front\s*end|coding|koding/, "Programmer / IT"],
  [/design\s*grafis|desain\s*grafis|graphic\s*designer|illustrator|ui\s*designer|ux\s*designer/, "Design Grafis"],
  [/videografer|video\s*editor|kameramen|filmmaker/, "Videografer"],
  [/wartawan|jurnalis|reporter|penulis\s*berita/, "Wartawan"],
  [/akuntan|accounting|pembukuan|staf\s*keuangan|finance/, "Akuntan"],
  [/pengacara|advokat|lawyer|konsultan\s*hukum/, "Pengacara"],
  [/notaris|ppat/, "Notaris"],
  [/makelar|agen\s*(properti|real\s*estate|asuransi)|broker/, "Makelar / Agen"],
  [/perawat|bidan|dokter|apoteker|analis\s*lab|medis|farmasi|paramedis|puskesmas|kesehatan/, "Tenaga Kesehatan"],
  [/security|satpam|guard|petugas\s*keamanan/, "Security / Satpam"],
  [/bumn|bank\s*(mandiri|bri|bca|btn)/, "Karyawan BUMN"],

  // Jasa — spesifik dulu
  [/rias|salon|kecantikan|makeup|mua|hair\s*stylist|tata\s*rias|skincare|skin\s*care/, "Rias / Salon / Kecantikan"],
  [/cat\s*sitter|pet\s*sitter|dog\s*walker|perawatan\s*hewan/, "Cat Sitter / Pet Sitter"],
  [/juru\s*masak|koki|chef/, "Juru Masak / Koki"],
  [/pelayan|waiter|waitress|pramusaji|barista|kasir\s*restoran/, "Pelayan / Barista / F&B"],
  [/tukang\s*cukur|barber|pangkas\s*rambut|hairstylist|potong\s*rambut/, "Tukang Cukur / Barber"],
  [/baby\s*sitter|babysitter|pengasuh/, "Baby Sitter / Pengasuh Anak"],
  [/pembantu|asisten\s*rumah\s*tangga|domestik/, "Pembantu / Asisten Rumah Tangga"],

  // Gig & Transportasi — spesifik dulu
  [/ojek\s*online|ojol|gojek|grab\s*motor/, "Ojek Online"],
  [/taksi\s*online|maxim|indrive|grab\s*car|sopir\s*travel|driver\s*taksi/, "Driver Taksi Online"],
  [/kurir|j&t|jne|shopee\s*express|ekspedisi|pengiriman/, "Kurir"],
  [/masinis|supir\s*kereta|kai|commuter/, "Masinis / Supir Kereta"],
  [/supir\s*(pribadi|bus|truk)|driver\s*(pribadi|bus)|busway|transjakarta|travel\s*driver/, "Supir / Driver Angkutan"],
  [/operator\s*pabrik|pekerja\s*produksi|operator\s*mesin/, "Operator Pabrik / Buruh"],
  [/staf\s*gudang|petugas\s*gudang|warehouse|logistik|packing|forklift/, "Petugas Gudang / Logistik"],
  [/pekerja\s*lepas|freelancer|harian\s*lepas|borongan|casual/, "Pekerja Lepas"],
  [/tukang\s*bangunan|tukang\s*(batu|kayu)|kuli\s*bangunan|mandor\s*bangunan/, "Tukang Bangunan"],
  [/tukang\s*servis\s*ac|teknisi\s*(ac|elektronik|hp|kulkas|mesin\s*cuci)/, "Tukang Servis AC"],
  [/montir|mekanik|bengkel|teknisi\s*otomotif/, "Montir / Bengkel"],

  // Wirausaha & Dagang
  [/pengusaha|owner|pemilik\s*usaha|direktur/, "Pengusaha"],
  [/pedagang|dagang|dagangan|reseller|dropshipper|penjual|warung|kaki\s*lima|toko/, "Pedagang"],
  [/wiraswasta|wirausaha|usaha\s*sendiri|umkm/, "Wiraswasta"],
  [/petani|pekebun|buruh\s*tani/, "Petani / Pekebun"],
  [/peternak|ternak|budidaya|ayam|sapi/, "Peternak"],
  [/nelayan|tangkap\s*ikan/, "Nelayan"],

  // Non-kerja — akhir
  [/pelajar|siswa|siswi|santri|maha?siswa|kuliah|sekolah|sma|smk|smp|sd|lulusan|fresh\s*graduate|belum\s*kerja|belum\s*bekerja|tidak\s*bekerja|mencari\s*kerja|penganggur|menganggur|nganggur/, "Pelajar / Mahasiswa / Belum Bekerja"],

  // Karyawan — catch-all paling umum
  [/karyawan|swasta|pegawai|staff|staf|marketing|sales|admin|office\s*boy|ob|pengisi\s*bbm|spbu|operator|buruh|pekerja|bekerja|kerja di/, "Karyawan Swasta"],
];

export function normalizePekerjaan(raw: string | null | undefined): string {
  if (!raw) return "";
  const s = raw.toLowerCase().trim().replace(/\s+/g, " ").replace(/[,.;:]+$/g, "").replace(/[()[\]{}]/g, "");
  if (!s || STOP.includes(s)) return "";
  // 1) exact alias
  if (ALIAS[s]) return ALIAS[s];
  // 2) keyword regex (first match)
  for (const [re, label] of KEYWORDS) {
    if (re.test(s)) return label;
  }
  // 3) fallback
  return "Lainnya";
}
